#!/system/bin/sh
/system/bin/pppd	\
/dev/ttyUSB0		\
115200			\
debug			\
noauth			\
user 			\
password PASSWD		\
defaultroute		\
noipdefault		\
usepeerdns		\
connect '/system/bin/chat -v -f /system/etc/ppp/chat.conf'
